### ISSUE TITLE
Ocl error

### ISSUE THREAD

**Issue by along02** [AnimeThemes/animethemes-batch-encoder#17]
**Describe the bug**
Having -af aresample=ocl=stereo,loudnorm... breaks the code. Changing it to -af aresample=ochl=stereo,loudnorm... fixes it. I'm using ffmpeg stable 5.1.2.

[aresample @ 0x600003c05d70] The "ocl" option is deprecated: set output channel layout (Deprecated, use ochl)
[libopus @ 0x147e101e0] Invalid channel layout 5.1(side) for specified mapping family -1.
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by ghost** [comment]
IMO this is a high priority ticket since this is a breaking change to the script for v5.1.2+ builds, and we want everyone using 6.X now.

**Comment by ghost** [comment]
Addressed in https://github.com/AnimeThemes/animethemes-batch-encoder/pull/20 by @Kyrch and targeted for 1.2
